src/UmamiNationBundle/Form/DefaultSettingsResolver.php
<?php

namespace UmamiNationBundle\Form;

/**
 * Class DefaultSettingsResolver
 * @package UmamiNationBundle\Form
 *
 * Finds Defaults Configuration for a specific Form Type in the given configuration
 *
 */
class DefaultSettingsResolver
{
    /**
     * @var array  assoc array with default values for all forms
     */
    private $defaults;

    /**
     * DefaultSettingsResolver constructor.
     * @param array $defaults
     *
     * Takes Default Settings Array from Configuration (config.yaml)
     * The config has to be structures like the namespaces inside the Form directory of
     * the bundle:
     * The subarray ["Port"]["SearchForm"] will be used for Type UmamiNationBundle\Form\Port\SearchForm.
     */
    public function __construct(array $defaults)
    {
        $this->defaults = $defaults;
    }

    /**
     * @param $type
     * @return array
     *
     * Tries to find default settings for a given form inside the default settings array.
     *
     * If settings for this form are found, the resulting sub-array is returned.
     */
    public function getDefaultsForForm($type): array
    {
        if (\is_object($type)) {
            $type = \get_class($type);
        }

        $type = \str_replace('UmamiNationBundle\\Form\\', '', $type);
        $path = \explode('\\', $type);
        $defaults = $this->defaults;
        foreach ($path as $pathItem) {
            if (!\array_key_exists($pathItem, $defaults)) {
                return [];
            }

            $defaults = $defaults[$pathItem];
        }

        return $defaults;
    }
}

src/UmamiNationBundle/Form/DefaultsSettingFormFactory.php
<?php

namespace UmamiNationBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;

/**
 * Class DefaultsSettingFormFactory
 * @package UmamiNationBundle\Form
 *
 * Makes forms with the standard SF2 Form Factory and sets default values
 */
class DefaultsSettingFormFactory implements FormFactoryInterface
{
    /**
     * @var FormFactoryInterface
     */
    private $factory;

    /**
     * @var DefaultSettingsResolver
     */
    private $resolver;

    /**
     * DefaultsSettingFormFactory constructor.
     * @param FormFactoryInterface $factory
     * @param DefaultSettingsResolver $resolver
     */
    public function __construct(FormFactoryInterface $factory, DefaultSettingsResolver $resolver)
    {
        $this->resolver = $resolver;
        $this->factory = $factory;
    }

    /**
     * {@inheritdoc}
     */
    public function create(
        $type = 'form',
        $data = null,
        array $options = []
    ): FormInterface {
        if ($data === null) {
            $data = $this->resolver->getDefaultsForForm($type);
        }

        return $this->factory->create($type, $data, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function createNamed($name, $type = 'form', $data = null, array $options = array()): FormInterface
    {
        return $this->factory->createNamed($name, $type, $data, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function createForProperty($class, $property, $data = null, array $options = array()): FormInterface
    {
        return $this->factory->createForProperty($class, $property, $data, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function createBuilder(
        $type = 'form',
        $data = null,
        array $options = []
    ): FormBuilderInterface {
        return $this->factory->createBuilder($type, $data, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function createNamedBuilder(
        $name,
        $type = 'form',
        $data = null,
        array $options = []
    ): FormBuilderInterface {
        return $this->factory->createNamedBuilder($name, $type, $data, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function createBuilderForProperty(
        $class,
        $property,
        $data = null,
        array $options = []
    ): FormBuilderInterface {
        return $this->factory->createBuilderForProperty($class, $property, $data, $options);
    }
}

src/UmamiNationBundle/Form/Order/SearchOrder.php
<?php

namespace UmamiNationBundle\Form\Order;

use UmamiNationBundle\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Translation\Exception\InvalidArgumentException;

/**
 * Class SearchOrder
 * @package UmamiNationBundle\Form\Order
 */
class SearchOrder extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @throws InvalidArgumentException
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod('get')
            ->add(
                'product',
                EntityType::class,
                [
                    'class' => Product::class,
                    'label' => 'umami-nation.order.form.label.product',
                    'placeholder' => 'umami-nation.order.form.placeholder.product',
                    'choice_label' => 'name',
                    'required' => false
                ]
            )
            ->add(
                'orderEnd',
                DateTimeType::class,
                [
                    'label' => 'umami-nation.order.form.label.order_from',
                    'required' => false,
                    'placeholder' => [
                        'year' => 'umami-nation.order.form.placeholder.year',
                        'month' => 'umami-nation.order.form.placeholder.month',
                        'day' => 'umami-nation.order.form.placeholder.day',
                        'hour' => 'umami-nation.order.form.placeholder.hour',
                        'minute' => 'umami-nation.order.form.placeholder.minute'
                    ]
                ]
            );
    }
}

src/UmamiNationBundle/Form/Product/NewProduct.php
<?php

namespace UmamiNationBundle\Form\Product;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class NewProduct
 * @package UmamiNationBundle\Form\Product
 */
class NewProduct extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod('post')
            ->add(
                'name',
                TextType::class,
                [
                    'label' => 'umami-nation.product.form.label.name',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.name'
                    ]
                ]
            )
            ->add(
                'price',
                NumberType::class,
                [
                    'label' => 'umami-nation.product.form.label.price',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.price'
                    ]
                ]
            )
            ->add(
                'recipe',
                TextareaType::class,
                [
                    'label' => 'umami-nation.product.form.label.recipe',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.recipe'
                    ]
                ]
            )
            ->add(
                'duration',
                NumberType::class,
                [
                    'label' => 'umami-nation.product.form.label.duration',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.duration'
                    ]
                ]
            );
    }
}

src/UmamiNationBundle/Form/Product/SearchProduct.php
<?php

namespace UmamiNationBundle\Form\Product;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class SearchProduct
 * @package UmamiNationBundle\Form\Product
 */
class SearchProduct extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod('get')
            ->add(
                'name',
                TextType::class,
                [
                    'label' => 'umami-nation.product.form.label.name',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.name'
                    ]
                ]
            )
            ->add(
                'price',
                NumberType::class,
                [
                    'label' => 'umami-nation.product.form.label.price',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.product.form.placeholder.price'
                    ]
                ]
            );
    }
}

src/UmamiNationBundle/Form/User/LocalesType.php
<?php

namespace UmamiNationBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Role\Role;

/**
 * Class LocalesType
 * @package UmamiNationBundle\Form\User
 */
class LocalesType extends AbstractType
{
    /** @var  Role[] */
    protected $locales;

    /**
     * LocalesType constructor.
     * @param $locales
     */
    public function __construct($locales)
    {
        $this->locales = $locales;
    }

    /**
     * @param OptionsResolver $resolver
     * @throws \Symfony\Component\OptionsResolver\Exception\AccessException
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'choices' => $this->getLocaleChoices()
        ]);
    }

    /**
     * @return Role[]
     */
    private function getLocaleChoices()
    {
        $locales = [];
        foreach ($this->locales as $locale => $value) {
            $locales[(string)$value] = $locale;
        }

        return $locales;
    }

    /**
     * @return null|string
     */
    public function getParent()
    {
        return ChoiceType::class;
    }
}

src/UmamiNationBundle/Form/User/RolesType.php
<?php

namespace UmamiNationBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;
use Symfony\Component\Security\Core\Role\Role;
use Symfony\Component\Security\Core\Role\RoleHierarchy;

/**
 * Class RolesType
 * @package UmamiNationBundle\Form\User
 */
class RolesType extends AbstractType
{
    /** @var  Role[] */
    protected $reachableRoles;
    /** @var Role[]  */
    protected $roleChoices;
    /** @var string  */
    private $transPrefix = 'umami-nation.security.roles.';

    /**
     * RolesType constructor.
     * @param RoleHierarchy $roleHierarchy
     * @param AuthorizationChecker $authorizationChecker
     */
    public function __construct(RoleHierarchy $roleHierarchy, AuthorizationChecker $authorizationChecker)
    {
        $superAdminRole = 'ROLE_SUPER_ADMIN';
        $currentPermissions = [new Role($superAdminRole)];
        $this->reachableRoles = $roleHierarchy->getReachableRoles($currentPermissions);
        $this->roleChoices = $this->getRoleChoices();
        if (!$authorizationChecker->isGranted($superAdminRole)) {
            unset($this->roleChoices[$this->transPrefix.$superAdminRole]);
        }
    }

    /**
     * @param OptionsResolver $resolver
     * @throws \Symfony\Component\OptionsResolver\Exception\AccessException
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'choices' => $this->getRoleChoices(),
            'choice_translation_domain' => true,
            'expanded' => false,
            'multiple' => false
        ]);
    }

    /**
     * @return Role[]
     */
    private function getRoleChoices()
    {
        $roles = [];
        /** @var Role $role**/
        foreach ($this->reachableRoles as $role) {
            $roleStr = $role->getRole();
            $roles[$this->transPrefix.$roleStr] = $roleStr;
        }

        return $roles;
    }

    /**
     * @return null|string
     */
    public function getParent()
    {
        return ChoiceType::class;
    }
}

src/UmamiNationBundle/Form/User/SearchUser.php
<?php

namespace UmamiNationBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class SearchUser
 * @package UmamiNationBundle\Form\User
 */
class SearchUser extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod('get')
            ->add(
                'username',
                TextType::class,
                [
                    'label' => 'umami-nation.user.form.label.name',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.user.form.placeholder.username'
                    ]
                ]
            )
            ->add(
                'email',
                NumberType::class,
                [
                    'label' => 'umami-nation.user.form.label.email',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.user.form.placeholder.email'
                    ]
                ]
            )
            ->add(
                'firstName',
                TextType::class,
                [
                    'label' => 'umami-nation.user.form.label.firstName',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.user.form.placeholder.firstName'
                    ]
                ]
            )->add(
                'lastName',
                TextType::class,
                [
                    'label' => 'umami-nation.user.form.label.lastName',
                    'required' => false,
                    'attr' => [
                        'placeholder' => 'umami-nation.user.form.placeholder.lastName'
                    ]
                ]
            )->add(
                'roles',
                RolesType::class,
                [
                    'label' => 'umami-nation.security.form.label.role',
                    'required' => false,
                    'placeholder' => 'umami-nation.user.form.placeholder.role'
                ]
            )
            ->add(
                'isActive',
                CheckboxType::class,
                [
                    'label' => 'umami-nation.user.form.label.only_active',
                    'required' => false,
                    'data' => true
                ]
            );
    }
}

src/UmamiNationBundle/Resources/views/Form/form_div_layout.html.twig
{# Widgets #}

{%- block form_widget -%}
    {% if compound %}
        {{- block('form_widget_compound') -}}
    {% else %}
        {{- block('form_widget_simple') -}}
    {% endif %}
{%- endblock form_widget -%}

{%- block form_widget_simple -%}
    {%- set type = type|default('text') -%}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{%- endblock form_widget_simple -%}

{%- block form_widget_compound -%}
    <div {{ block('widget_container_attributes') }}>
        {%- if form.parent is empty -%}
            {{ form_errors(form) }}
        {%- endif -%}
        {{- block('form_rows') -}}
        {{- form_rest(form) -}}
    </div>
{%- endblock form_widget_compound -%}

{%- block collection_widget -%}
    {% if prototype is defined %}
        {%- set attr = attr|merge({'data-prototype': form_row(prototype) }) -%}
    {% endif %}
    {{- block('form_widget') -}}
{%- endblock collection_widget -%}

{%- block textarea_widget -%}
    <textarea {{ block('widget_attributes') }}>{{ value }}</textarea>
{%- endblock textarea_widget -%}

{%- block choice_widget -%}
    {% if expanded %}
        {{- block('choice_widget_expanded') -}}
    {% else %}
        {{- block('choice_widget_collapsed') -}}
    {% endif %}
{%- endblock choice_widget -%}

{%- block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
    {%- for child in form %}
        {{- form_widget(child) -}}
        {{- form_label(child, null, {translation_domain: choice_translation_domain}) -}}
    {% endfor -%}
    </div>
{%- endblock choice_widget_expanded -%}

{%- block choice_widget_collapsed -%}
    {%- if required and placeholder is none and not placeholder_in_choices and not multiple and (attr.size is not defined or attr.size <= 1) -%}
        {% set required = false %}
    {%- endif -%}
    <select {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {%- if placeholder is not none -%}
            <option value=""{% if required and value is empty %} selected="selected"{% endif %}>{{ placeholder != '' ? (translation_domain is same as(false) ? placeholder : placeholder|trans({}, translation_domain)) }}</option>
        {%- endif -%}
        {%- if preferred_choices|length > 0 -%}
            {% set options = preferred_choices %}
            {{- block('choice_widget_options') -}}
            {%- if choices|length > 0 and separator is not none -%}
                <option disabled="disabled">{{ separator }}</option>
            {%- endif -%}
        {%- endif -%}
        {%- set options = choices -%}
        {{- block('choice_widget_options') -}}
    </select>
{%- endblock choice_widget_collapsed -%}

{%- block choice_widget_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            <optgroup label="{{ choice_translation_domain is same as(false) ? group_label : group_label|trans({}, choice_translation_domain) }}">
                {% set options = choice %}
                {{- block('choice_widget_options') -}}
            </optgroup>
        {%- else -%}
            <option value="{{ choice.value }}"{% if choice.attr %}{% with { attr: choice.attr } %}{{ block('attributes') }}{% endwith %}{% endif %}{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ choice_translation_domain is same as(false) ? choice.label : choice.label|trans({}, choice_translation_domain) }}</option>
        {%- endif -%}
    {% endfor %}
{%- endblock choice_widget_options -%}

{%- block checkbox_widget -%}
    <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{%- endblock checkbox_widget -%}

{%- block radio_widget -%}
    <input type="radio" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{%- endblock radio_widget -%}

{%- block datetime_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form.date) -}}
            {{- form_errors(form.time) -}}
            {{- form_widget(form.date) -}}
            {{- form_widget(form.time) -}}
        </div>
    {%- endif -%}
{%- endblock datetime_widget -%}

{%- block date_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw -}}
        </div>
    {%- endif -%}
{%- endblock date_widget -%}

{%- block time_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        {%- set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} -%}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif -%}
{%- endblock time_widget -%}

{%- block dateinterval_widget -%}
    {%- if widget == 'single_text' -%}
        {{- block('form_widget_simple') -}}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form) -}}
            <table class="{{ table_class|default('') }}">
                <thead>
                    <tr>
                        {%- if with_years %}<th>{{ form_label(form.years) }}</th>{% endif -%}
                        {%- if with_months %}<th>{{ form_label(form.months) }}</th>{% endif -%}
                        {%- if with_weeks %}<th>{{ form_label(form.weeks) }}</th>{% endif -%}
                        {%- if with_days %}<th>{{ form_label(form.days) }}</th>{% endif -%}
                        {%- if with_hours %}<th>{{ form_label(form.hours) }}</th>{% endif -%}
                        {%- if with_minutes %}<th>{{ form_label(form.minutes) }}</th>{% endif -%}
                        {%- if with_seconds %}<th>{{ form_label(form.seconds) }}</th>{% endif -%}
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {%- if with_years %}<td>{{ form_widget(form.years) }}</td>{% endif -%}
                        {%- if with_months %}<td>{{ form_widget(form.months) }}</td>{% endif -%}
                        {%- if with_weeks %}<td>{{ form_widget(form.weeks) }}</td>{% endif -%}
                        {%- if with_days %}<td>{{ form_widget(form.days) }}</td>{% endif -%}
                        {%- if with_hours %}<td>{{ form_widget(form.hours) }}</td>{% endif -%}
                        {%- if with_minutes %}<td>{{ form_widget(form.minutes) }}</td>{% endif -%}
                        {%- if with_seconds %}<td>{{ form_widget(form.seconds) }}</td>{% endif -%}
                    </tr>
                </tbody>
            </table>
            {%- if with_invert %}{{ form_widget(form.invert) }}{% endif -%}
        </div>
    {%- endif -%}
{%- endblock dateinterval_widget -%}

{%- block number_widget -%}
    {# type="number" doesn't work with floats #}
    {%- set type = type|default('text') -%}
    {{ block('form_widget_simple') }}
{%- endblock number_widget -%}

{%- block integer_widget -%}
    {%- set type = type|default('number') -%}
    {{ block('form_widget_simple') }}
{%- endblock integer_widget -%}

{%- block money_widget -%}
    {{ money_pattern|replace({ '{{ widget }}': block('form_widget_simple') })|raw }}
{%- endblock money_widget -%}

{%- block url_widget -%}
    {%- set type = type|default('url') -%}
    {{ block('form_widget_simple') }}
{%- endblock url_widget -%}

{%- block search_widget -%}
    {%- set type = type|default('search') -%}
    {{ block('form_widget_simple') }}
{%- endblock search_widget -%}

{%- block percent_widget -%}
    {%- set type = type|default('text') -%}
    {{ block('form_widget_simple') }} %
{%- endblock percent_widget -%}

{%- block password_widget -%}
    {%- set type = type|default('password') -%}
    {{ block('form_widget_simple') }}
{%- endblock password_widget -%}

{%- block hidden_widget -%}
    {%- set type = type|default('hidden') -%}
    {{ block('form_widget_simple') }}
{%- endblock hidden_widget -%}

{%- block email_widget -%}
    {%- set type = type|default('email') -%}
    {{ block('form_widget_simple') }}
{%- endblock email_widget -%}

{%- block range_widget -%}
    {% set type = type|default('range') %}
    {{- block('form_widget_simple') -}}
{%- endblock range_widget %}

{%- block button_widget -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
                '%name%': name,
                '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</button>
{%- endblock button_widget -%}

{%- block submit_widget -%}
    {%- set type = type|default('submit') -%}
    {{ block('button_widget') }}
{%- endblock submit_widget -%}

{%- block reset_widget -%}
    {%- set type = type|default('reset') -%}
    {{ block('button_widget') }}
{%- endblock reset_widget -%}

{# Labels #}

{%- block form_label -%}
    {% if label is not same as(false) -%}
        {% if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {% if required -%}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {% if label is empty -%}
            {%- if label_format is not empty -%}
                {% set label = label_format|replace({
                    '%name%': name,
                    '%id%': id,
                }) %}
            {%- else -%}
                {% set label = name|humanize %}
            {%- endif -%}
        {%- endif -%}
        <label{% if label_attr %}{% with { attr: label_attr } %}{{ block('attributes') }}{% endwith %}{% endif %}>{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</label>
    {%- endif -%}
{%- endblock form_label -%}

{%- block button_label -%}{%- endblock -%}

{# Rows #}

{%- block repeated_row -%}
    {#
    No need to render the errors here, as all errors are mapped
    to the first child (see RepeatedTypeValidatorExtension).
    #}
    {{- block('form_rows') -}}
{%- endblock repeated_row -%}

{%- block form_row -%}
    <div>
        {{- form_label(form) -}}
        {{- form_errors(form) -}}
        {{- form_widget(form) -}}
    </div>
{%- endblock form_row -%}

{%- block button_row -%}
    <div>
        {{- form_widget(form) -}}
    </div>
{%- endblock button_row -%}

{%- block hidden_row -%}
    {{ form_widget(form) }}
{%- endblock hidden_row -%}

{# Misc #}

{%- block form -%}
    {{ form_start(form) }}
        {{- form_widget(form) -}}
    {{ form_end(form) }}
{%- endblock form -%}

{%- block form_start -%}
    {% set method = method|upper %}
    {%- if method in ["GET", "POST"] -%}
        {% set form_method = method %}
    {%- else -%}
        {% set form_method = "POST" %}
    {%- endif -%}
    <form name="{{ name }}" method="{{ form_method|lower }}"{% if action != '' %} action="{{ action }}"{% endif %}{% for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}{% if multipart %} enctype="multipart/form-data"{% endif %}>
    {%- if form_method != method -%}
        <input type="hidden" name="_method" value="{{ method }}" />
    {%- endif -%}
{%- endblock form_start -%}

{%- block form_end -%}
    {%- if not render_rest is defined or render_rest -%}
        {{ form_rest(form) }}
    {%- endif -%}
    </form>
{%- endblock form_end -%}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
    <ul>
        {%- for error in errors -%}
            <li>{{ error.message }}</li>
        {%- endfor -%}
    </ul>
    {%- endif -%}
{%- endblock form_errors -%}

{%- block form_rest -%}
    {% for child in form -%}
        {% if not child.rendered %}
            {{- form_row(child) -}}
        {% endif %}
    {%- endfor %}
{% endblock form_rest %}

{# Support #}

{%- block form_rows -%}
    {% for child in form %}
        {{- form_row(child) -}}
    {% endfor %}
{%- endblock form_rows -%}

{%- block widget_attributes -%}
    id="{{ id }}" name="{{ full_name }}"
    {%- if disabled %} disabled="disabled"{% endif -%}
    {%- if required %} required="required"{% endif -%}
    {{ block('attributes') }}
{%- endblock widget_attributes -%}

{%- block widget_container_attributes -%}
    {%- if id is not empty %}id="{{ id }}"{% endif -%}
    {{ block('attributes') }}
{%- endblock widget_container_attributes -%}

{%- block button_attributes -%}
    id="{{ id }}" name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif -%}
    {{ block('attributes') }}
{%- endblock button_attributes -%}

{% block attributes -%}
    {%- for attrname, attrvalue in attr -%}
        {{- " " -}}
        {%- if attrname in ['placeholder', 'title'] -%}
            {{- attrname }}="{{ translation_domain is same as(false) ? attrvalue : attrvalue|trans({}, translation_domain) }}"
        {%- elseif attrvalue is same as(true) -%}
            {{- attrname }}="{{ attrname }}"
        {%- elseif attrvalue is not same as(false) -%}
            {{- attrname }}="{{ attrvalue }}"
        {%- endif -%}
    {%- endfor -%}
{%- endblock attributes -%}